# Generated by Django 5.1.6 on 2025-03-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idNumber', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=50)),
                ('middleInitial', models.CharField(max_length=5)),
                ('suffix', models.CharField(max_length=5)),
                ('corporate_email', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passNumber', models.CharField(max_length=10)),
                ('passExpire', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badgeNumber', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=50)),
                ('middleInitial', models.CharField(max_length=5)),
                ('suffix', models.CharField(max_length=5)),
                ('corporate_email', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lastName', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=25)),
                ('suffix', models.CharField(max_length=5)),
                ('dl_number', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('corporate_email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plateNumber', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('chassisNumber', models.CharField(max_length=15)),
                ('OR_Number', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicationNumber', models.CharField(max_length=25)),
                ('files', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate_pass.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate_pass.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate_pass.pass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate_pass.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate_pass.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
