# Generated by Django 5.1.7 on 2025-04-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0007_paymenttransaction_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.cashierprofile'),
        ),
    ]
