# Generated by Django 5.2 on 2025-05-18 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('admin_id', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('cashier_id', models.CharField(max_length=15)),
                ('job_title', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrationNumber', models.BigAutoField(primary_key=True, serialize=False)),
                ('files', models.URLField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('for payment', 'For Payment'), ('reviewing documents', 'Reviewing Documents'), ('for final inspection', 'For Final Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('badgeNumber', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('corporate_email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('dl_number', models.CharField(blank=True, max_length=15, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('security', 'Security'), ('cashier', 'Cashier'), ('admin', 'Admin')], default='user', max_length=20, null=True)),
                ('school_role', models.CharField(choices=[('student', 'Student'), ('faculty', 'faculty'), ('university personnel', 'University Personnel')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('void', 'Void')], default='pending', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=75, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.adminprofile')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.cashierprofile')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.registration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_inspection_date', models.DateTimeField(auto_now_add=True)),
                ('physical_final_inspection_date', models.DateField()),
                ('remarks', models.CharField(choices=[('to be inspected', 'To Be Inspected'), ('sticker released', 'Sticker Released'), ('application declined', 'Application Declined'), ('request refund', 'To Request Refund')], default='to_be_inspected', max_length=30)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('payment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.paymenttransaction')),
                ('security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.securityprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='securityprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.userprofile'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.userprofile'),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('alert', 'Alert')], max_length=20)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_posted', to='vehicle_pass.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cashierprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.userprofile'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_posted', to='vehicle_pass.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.userprofile'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plateNumber', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('chassisNumber', models.CharField(max_length=17)),
                ('OR_Number', models.CharField(max_length=15)),
                ('CR_Number', models.CharField(max_length=9)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_legal_owner', models.BooleanField(default=False)),
                ('owner_firstname', models.CharField(blank=True, max_length=45, null=True)),
                ('owner_middlename', models.CharField(blank=True, max_length=45, null=True)),
                ('owner_lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('owner_suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('relationship_to_owner', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=13, null=True)),
                ('self_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.vehicle'),
        ),
        migrations.CreateModel(
            name='VehiclePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passNumber', models.CharField(max_length=10)),
                ('passExpire', models.DateField()),
                ('claim_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], max_length=10)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
