# Generated by Django 5.2 on 2025-05-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'faculty'), ('university personnel', 'University Personnel')], max_length=20, null=True),
        ),
    ]
