# Generated by Django 5.2 on 2025-04-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_middlename',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
