# Generated by Django 5.2 on 2025-04-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0002_alter_owner_owner_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
