# Generated by Django 5.2 on 2025-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0002_emailtemplate_notificationqueue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
