# Generated by Django 5.1.7 on 2025-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0002_remove_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='plate_number',
            new_name='vehicle',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
