# Generated by Django 5.2 on 2025-05-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0002_alter_userprofile_school_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty'), ('university personnel', 'University Personnel')], max_length=20, null=True),
        ),
    ]
