# Generated by Django 5.2 on 2025-10-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0003_alter_registration_signature_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityprofile',
            name='level',
            field=models.CharField(choices=[('guard', 'Security Guard/Personnel'), ('oic', 'Security OIC'), ('gso director', 'GSO - Director')], default='guard', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_level',
            field=models.CharField(blank=True, choices=[('first year', 'First Year'), ('second year', 'Second Year'), ('third year', 'Third Year'), ('fourth year', 'Fourth year'), ('fifth year', 'Fifth Year')], max_length=40, null=True),
        ),
    ]
