# Generated by Django 5.1.2 on 2025-05-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0003_alter_userprofile_school_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='physical_final_inspection_date',
            field=models.DateField(null=True),
        ),
    ]
