# Generated by Django 5.1.7 on 2025-03-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0003_rename_plate_number_registration_vehicle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='middle_initial',
            new_name='middle_name',
        ),
    ]
