# Generated by Django 5.2 on 2025-05-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0003_alter_userprofile_school_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_legal_owner',
        ),
    ]
