# Generated by Django 5.2 on 2025-05-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0004_alter_inspectionreport_physical_final_inspection_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='self_owner',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='color',
            new_name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_legal_owner',
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='physical_final_inspection_date',
            field=models.DateField(),
        ),
    ]
