# Generated by Django 5.2 on 2025-05-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0004_remove_vehicle_is_legal_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='color',
            new_name='vehicle_color',
        ),
    ]
