# Generated by Django 5.2 on 2025-11-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0004_securityprofile_level_alter_userprofile_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle_pass.userprofile'),
        ),
    ]
