# Generated by Django 5.1.7 on 2025-03-31 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0005_userprofile_role_alter_announcement_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_posted', to='vehicle_pass.userprofile'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_posted', to='vehicle_pass.userprofile'),
        ),
    ]
