# Generated by Django 5.2 on 2025-05-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0005_rename_self_owner_vehicle_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='physical_final_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
