# Generated by Django 5.2 on 2025-05-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0005_rename_color_vehicle_vehicle_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='self_owner',
            new_name='applicant',
        ),
    ]
