# Generated by Django 5.2 on 2025-12-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0006_alter_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('no application', 'No Application'), ('application submitted', 'Pending Initial Approval (OIC)'), ('initial approval', 'Initial Approved (Waiting for GSO Director)'), ('approved', 'Approved (Ready for Release)'), ('sticker released', 'Vehicle Pass Sticker Released'), ('rejected', 'Rejected')], default='no application', max_length=85),
        ),
    ]
