# Generated by Django 5.1.7 on 2025-04-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0006_remove_notification_recipient_notification_posted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
