# Generated by Django 5.2 on 2025-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0007_registration_document_reviewed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepass',
            name='claim_date',
        ),
        migrations.AlterField(
            model_name='vehiclepass',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='active', max_length=10),
        ),
    ]
