# Generated by Django 5.1.7 on 2025-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0008_alter_paymenttransaction_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='receipt_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
