# Generated by Django 5.2 on 2025-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_pass', '0009_alter_paymenttransaction_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('security', 'Security'), ('cashier', 'Cashier'), ('admin', 'Admin')], default='user', max_length=20, null=True),
        ),
    ]
